### ISSUE TITLE
自定第三方验证namespace无效，导致角色名称过长无法进入服务器

### ISSUE THREAD

**Issue by w123456w30w** [YuxuanZuo/MultiYggdrasil#13]
使用-Dmultiyggdrasil.namespace自定义第三方验证服务器的角色名称后缀无法生效，始终默认为custom
角色ID比较长的时候进入服务器会报错the received string length is longer than maximum allowed (18>16)将玩家踢出游戏

**Comment by YuxuanZuo** [comment]
抱歉，这部分好像忘写逻辑了（

**Comment by YuxuanZuo** [comment]
你好，```-Dmultiyggdrasil.namespace```这个参数是有效的，请检查你的设置是否正确，正确参数格式应为```-Dmultiyggdrasil.namespace=xyz```

**Comment by w123456w30w** [comment]
> 你好，`-Dmultiyggdrasil.namespace`这个参数是有效的，请检查你的设置是否正确，正确参数格式应为`-Dmultiyggdrasil.namespace=xyz`

抱歉隔了这么久才回复，是我在自定义名称的时候加入了大写字母导致的问题，请问为什么不允许大写字母出现在参数中呢？
