### ISSUE TITLE
无论玩家使用什么验证服务器，都强制玩家使用UUID v3

### ISSUE THREAD

**Issue by Silverteal** [YuxuanZuo/MultiYggdrasil#19]
这会将多种验证服务器的同名玩家视为同一玩家，有助于从离线验证迁移。这应该是可选功能。

**Comment by YuxuanZuo** [comment]
不是很明白您的意思，能详细解释一下吗

**Comment by Silverteal** [comment]
增加一个选项“强制使用离线UUID”，启用时，当玩家加入服务器时，返回的玩家profile中的UUID应该总是由用户名生成的“离线UUID”，即readme中所述UUID v3，这是因为同一个玩家可能有时会正版登录，有时会第三方登录。这个选项可以使他们在使用同一个用户名登录时获得相同的玩家profile。虽然这可能存在潜在的安全问题（玩家改名），但可以通过合理配置避免。

**Comment by YuxuanZuo** [comment]
但是目前这个API https://sessionserver.mojang.com/session/minecraft/profile/{uuid} 是根据uuid版本来决定向哪个服务器查询的，如果混用的话这个api没法处理
