### ISSUE TITLE
[Request] Patcher for server/authlib jarfile

### ISSUE THREAD

**Issue by amantewhiskey** [YuxuanZuo/MultiYggdrasil#5]
Hello, I'm testing MultiYggdrasil in my private home server and it works great! However, I found it difficult to move this setup to a hosted server since most providers don't allow to change the JVM startup flags which prevents people from replacing the javaagent.

I have been searching for solutions and none of the existing ones works with MultiYggdrasil, but I found [this](https://github.com/MrLetsplay2003/ShittyAuthPatcher) which is meant to be used with a different auth solution. I was wondering if you could try to make a similar tool to patch authlib/servers with MultiYggdrasil, setting the auth server and the additional options during the patch process.

Thanks for reading this, and thanks a lot for developing MultiYggdrasil ^-^

**Comment by YuxuanZuo** [comment]
Hello, your request is indeed technically possible, but I don't think this part of the functionality should be implemented in multiyggdrasil, I actually know of an alternative implementation who works well with my friend's server provider
[LaunchHelper](https://github.com/Codex-in-somnio/LaunchHelper) 
Good luck :)
